### ISSUE TITLE
JWTVerifier and verify() are thread safe?

### ISSUE THREAD

**Issue by joolfe** [auth0/java-jwt#260] opened 2018-06-08 08:04 UTC
Hi,

In an sever application like springboot API, can i create a instance of JWTVerifier and the reuse it even if more than one thread is using at same time or should i create a instance for each thread to avoid errors?

Best Regards.

**Comment by lbalmaceda** [comment] 2018-06-08 14:14
Yes, they are meant to be reusable. You shouldn't have any thread problems. 
Closing as dupe of https://github.com/auth0/java-jwt/issues/108.

**Closed by lbalmaceda** 2018-06-08 14:14 UTC
