### ISSUE TITLE
Can't use with JDK 1.7 throw java.lang.UnsupportedClassVersionError

### ISSUE THREAD

**Issue by anatoly314** [auth0/java-jwt#119] opened 2016-12-12 17:40 UTC
Trying to use 3.0.1 library, downloaded from Maven repository at Websphere 8.5 in project which build with JDK 1.7 but it throws the following error:

`java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/auth0/jwt/algorithms/Algorithm, offset=6`

I've tried to recompile from source but it didn't help, maybe I've done something wrong because it's first time I using gradle. 

Can somebody help me with this issue?

**Comment by hzalaz** [comment] 2016-12-12 17:43
It's a duplicate of #115 and as stated we need to the value specified in the issue. Will try to address it this week,  PRs are welcomed.

**Closed by hzalaz** 2016-12-12 17:43 UTC
Labels: duplicate

**Comment by anatoly314** [comment] 2016-12-13 10:49
I'd be happy to PR you but I don't know how? I've downloaded source code and compiled it locally without changing anything in `build.gradle` file and it just worked. I can upload your my `*.jar` file but doubt if it will help you.
