### ISSUE TITLE
NoSuchMethodError: No static method encodeBase64URLSafeString

### ISSUE THREAD

**Issue by ycoupe** [auth0/java-jwt#259] opened 2018-06-08 07:49 UTC
Hi I have a problem when I create a jwt token like this (I'm on Android):

```
try {
    Algorithm algorithm = Algorithm.HMAC256("secret");
    String token = JWT.create()
        .withIssuer("auth0")
        .sign(algorithm);
} catch (JWTCreationException exception){
    //Invalid Signing configuration / Couldn't convert Claims.
}
```

I have this error:

`
java.lang.NoSuchMethodError: No static method encodeBase64URLSafeString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Base64; or its super classes (declaration of 'org.apache.commons.codec.binary.Base64' appears in /system/framework/org.apache.http.legacy.boot.jar)
        at com.auth0.jwt.JWTCreator.sign(JWTCreator.java:330)
        at com.auth0.jwt.JWTCreator.access$100(JWTCreator.java:24)
        at com.auth0.jwt.JWTCreator$Builder.sign(JWTCreator.java:311)
`

This is my configuration: 

ext.androidConfig = [
        buildToolsVersion       : '27.0.3',
        compileSdkVersion       : 27,
        minSdkVersion           : 17,
        targetSdkVersion        : 27
]

kotlin                           : '1.2.41'
jsonWebToken            : '3.3.0'

Thanks for your help.

**Comment by lbalmaceda** [comment] 2018-06-08 14:10
@ycoupe This library was not made with Android in mind. If you need to decode a token you can still use [this other library](https://github.com/auth0/JWTDecode.Android). 

Closing as dupe of [many issues](https://github.com/auth0/java-jwt/issues?utf8=%E2%9C%93&q=is%3Aissue+android+nosuchmethoderror+is%3Aclosed+).

**Closed by lbalmaceda** 2018-06-08 14:10 UTC
